name: Backup GitHub Repository to Cloudflare R2 Bucket

on:
  push:
    branches:
      - master
jobs:
  back-up:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        repo:
          [
            "github.com/LucidumInc/update-manager.git",
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install @larose/git-backup
        run: npm install -g @larose/git-backup

      - name: Backing up repository ${{ github.event.repository.name }}
        run: |
          git-backup snapshot \
            --repo https://${{ secrets.BACKUP_PAT }}@${{ matrix.repo }} \
            --remote ${{ secrets.BACKUP_LOCATION }}/${{ github.event.repository.name }}/${{ github.ref_name }} \
            --access-key-id ${{ secrets.BACKUP_ACCESS_KEY_ID }} \
            --secret-access-key ${{ secrets.BACKUP_SECRET_ACCESS_KEY }}
