name: update-manager continuous integration

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
        python-version: [ 3.6, 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2

      - name: use set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: use latest pip
        run: pip install --upgrade pip

      - name: install python test deps
        run: pip install -r requirements_test.txt

      - name: install python package deps
        run: pip install -r requirements.txt

      - name: list python packages
        run: pip list

      - name: lint python code with pylint
        run: pylint --disable=missing-function-docstring,line-too-long,missing-module-docstring,invalid-name,trailing-newlines,bare-except,too-few-public-methods *.py

      - name: lint python code with flake8
        run: flake8 . --count --statistics

      - name: unit test python code
        run: echo unit

      - name: integration test python code
        run: echo integration

      - name: publish package
        run: echo publish package
